import {
  GovernanceUser,
  WhistleblowerDossier,
  FinancialRequisition,
  SongArrangement,
  AttendanceRecord,
  ParliamentaryAgendaItem,
  DigitalPetition,
} from "@/types/governance";

// Pure Genesis Vacant State - All constitutional offices are officially VACANT
export const INITIAL_PERSONAS: GovernanceUser[] = [
  {
    id: "office-tier1-advisor",
    legalName: "VACANT (পদ শূন্য)",
    email: "advisor.vacant@northsouth.edu",
    studentId: "UNASSIGNED",
    tier: 1,
    tierLabel: "Tier 1: Faculty Advisor (Vacant)",
    roleTitle: "Faculty Advisor & Tribunal Authority",
    department: "Office of Student Affairs (OSA)",
    isActing: false,
    permissions: ["whistleblower:unblinded", "requisition:tier3:approve", "audit:certify"],
  },
  {
    id: "office-tier2-president",
    legalName: "VACANT (পদ শূন্য)",
    email: "president.vacant@northsouth.edu",
    studentId: "UNASSIGNED",
    tier: 2,
    tierLabel: "Tier 2: Club President (Vacant)",
    roleTitle: "President & Chief Executive Officer",
    department: "Executive Board",
    isActing: false,
    permissions: ["requisition:tier2:dual_sign", "meeting:convoke", "vacancy:appoint"],
  },
  {
    id: "office-tier3-vp",
    legalName: "VACANT (পদ শূন্য)",
    email: "vp.vacant@northsouth.edu",
    studentId: "UNASSIGNED",
    tier: 3,
    tierLabel: "Tier 3: Vice President (Vacant)",
    roleTitle: "Vice President (Operations Oversight)",
    department: "Executive Board",
    isActing: false,
    actingRole: "Acting President (Standby)",
    permissions: ["operations:oversight", "logistics:view", "performance:view"],
  },
  {
    id: "office-tier3-gs",
    legalName: "VACANT (পদ শূন্য)",
    email: "gs.vacant@northsouth.edu",
    studentId: "UNASSIGNED",
    tier: 3,
    tierLabel: "Tier 3: General Secretary (Vacant)",
    roleTitle: "General Secretary & Parliamentary Custodian",
    department: "Secretariat",
    isActing: false,
    permissions: ["attendance:dispute", "resignation:queue", "minutes:publish"],
  },
  {
    id: "office-tier3-treasurer",
    legalName: "VACANT (পদ শূন্য)",
    email: "treasurer.vacant@northsouth.edu",
    studentId: "UNASSIGNED",
    tier: 3,
    tierLabel: "Tier 3: Treasurer (Vacant)",
    roleTitle: "Treasurer & Financial Custodian",
    department: "Treasury",
    isActing: false,
    permissions: ["ledger:manage", "requisition:disburse", "petty_cash:monitor"],
  },
  {
    id: "office-tier4-music",
    legalName: "VACANT (পদ শূন্য)",
    email: "music.head.vacant@northsouth.edu",
    studentId: "UNASSIGNED",
    tier: 4,
    tierLabel: "Tier 4: Music Department Head (Vacant)",
    roleTitle: "Music & Performance Director (Section 12 Lead)",
    department: "Music & Performance",
    isActing: false,
    isCreativeLead: true,
    permissions: ["creative:firewall:write", "repertoire:manage", "vocal:cast"],
  },
  {
    id: "office-tier4-logistics",
    legalName: "VACANT (পদ শূন্য)",
    email: "logistics.head.vacant@northsouth.edu",
    studentId: "UNASSIGNED",
    tier: 4,
    tierLabel: "Tier 4: Event & Logistics Head (Vacant)",
    roleTitle: "Event & Logistics Director (Gate Pass Authority)",
    department: "Event & Logistics",
    isActing: false,
    permissions: ["logistics:manage", "gatepass:issue", "venue:coordinate"],
  },
  {
    id: "office-tier4-media",
    legalName: "VACANT (পদ শূন্য)",
    email: "media.head.vacant@northsouth.edu",
    studentId: "UNASSIGNED",
    tier: 4,
    tierLabel: "Tier 4: Media & Design Head (Vacant)",
    roleTitle: "Media & Design Director (Brand Custodian)",
    department: "Media & Design",
    isActing: false,
    permissions: ["media:manage", "brand:custody", "digital:dual_admin"],
  },
  {
    id: "office-tier4-mm",
    legalName: "VACANT (পদ শূন্য)",
    email: "mm.head.vacant@northsouth.edu",
    studentId: "UNASSIGNED",
    tier: 4,
    tierLabel: "Tier 4: Member Management Head (Vacant)",
    roleTitle: "Member Management & Internal Discipline Head",
    department: "Member Management & Discipline",
    isActing: false,
    permissions: ["attendance:track", "showcause:issue", "coordinator:manage"],
  },
  {
    id: "office-tier4-sponsorship",
    legalName: "VACANT (পদ শূন্য)",
    email: "sponsorship.head.vacant@northsouth.edu",
    studentId: "UNASSIGNED",
    tier: 4,
    tierLabel: "Tier 4: Sponsorship Head (Vacant)",
    roleTitle: "Sponsorship & Partnership Director (In-Kind Register)",
    department: "Sponsorship & Partnership",
    isActing: false,
    permissions: ["sponsorship:manage", "inkind:record", "corporate:liaison"],
  },
  {
    id: "unassigned-observer",
    legalName: "VACANT (পদ শূন্য)",
    email: "observer@northsouth.edu",
    studentId: "UNASSIGNED",
    tier: 5,
    tierLabel: "Tier 5: Institutional Observer",
    roleTitle: "General Assembly (Institutional Observer)",
    department: "General Assembly",
    isActing: false,
    permissions: ["profile:view", "leave:submit", "parliament:vote", "petition:sign"],
  },
];

export const INITIAL_DOSSIERS: WhistleblowerDossier[] = [
  {
    id: "DOS-2026-001",
    trackingNumber: "WB-NSU-2026-001",
    targetRole: "Executive Office",
    targetName: "Office of the President (Under Review)",
    allegationType: "FINANCIAL_MISCONDUCT",
    summary:
      "Confidential disclosure regarding off-book vendor sponsorship negotiation for the Fall Gala without Treasury pre-clearance.",
    evidenceCount: 4,
    submittedAt: "2026-09-24T14:32:00Z",
    status: "CONFIDENTIAL_REVIEW",
    isAgainstPresident: true,
  },
];

export const INITIAL_REQUISITIONS: FinancialRequisition[] = [
  {
    id: "REQ-2026-001",
    requisitionNumber: "ERF-2026-001",
    tier: 2,
    requestedBy: "Event & Logistics Department",
    initiatorRole: "Event & Logistics Head (Acting / Vacant)",
    department: "Event & Logistics",
    amountBDT: 14500,
    purpose: "Sound engineering engineer retainer and direct-box equipment rental under Annexure 'খ'",
    vendorName: "Studio SoundTech Dhaka",
    hasEBResolution: true,
    status: "PENDING_APPROVAL",
    signatures: {
      gsSigned: false,
      treasurerSigned: false,
      presidentSigned: false,
    },
    createdAt: "2026-09-29T10:30:00Z",
  },
];

export const INITIAL_REPERTOIRE: SongArrangement[] = [
  {
    id: "SONG-01",
    title: "Dhitang Dhitang Bole",
    genre: "Contemporary Folk Fusion",
    tempoBpm: 118,
    keySignature: "D minor",
    leadVocal: "Ensemble Lead (Audition Scheduled)",
    harmonies: ["Harmonized SATB Choral Ensemble"],
    instrumentation: ["Flute", "Acoustic Guitar", "Cajon", "Dotara"],
    status: "REHEARSAL_READY",
    section12Protected: true,
    lastEditedBy: "Music Department (Section 12 Lead)",
  },
  {
    id: "SONG-02",
    title: "O Amar Desher Mati",
    genre: "Patriotic Symphony",
    tempoBpm: 76,
    keySignature: "F major",
    leadVocal: "Choral Full Ensemble",
    harmonies: ["Choral SATB Section (16 Voices)"],
    instrumentation: ["Grand Piano", "Violin Ensembles", "Cello"],
    status: "LOCKED_FOR_CONCERT",
    section12Protected: true,
    lastEditedBy: "Music Department (Section 12 Lead)",
  },
];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  {
    memberId: "office-tier4-music",
    memberName: "Music Department Head (Vacant)",
    studentId: "UNASSIGNED",
    totalSessions: 14,
    attendedSessions: 14,
    excusedLeaves: 0,
    effectivePercentage: 100,
    consecutiveAbsences: 0,
    showCauseIssued: false,
    status: "IN_GOOD_STANDING",
  },
];

export const INITIAL_PARLIAMENTARY_AGENDAS: ParliamentaryAgendaItem[] = [
  {
    id: "AGENDA-2026-F1",
    agendaCode: "NSU-SOP-AG-01",
    title: "Ratification of Fall 2026 Operational Budget Allocation (Line-Item Compliance)",
    description:
      "Formal General Assembly ratification of the operational budget allocation, ensuring OSA line-item compliance and reserve maintenance.",
    category: "BUDGET_RATIFICATION",
    activeQuorumPercentage: 78.4,
    floorQuorumThreshold: 40.0,
    status: "OPEN",
    votesInFavor: 0,
    votesAgainst: 0,
    abstentions: 0,
    conflictedMembers: ["office-tier3-treasurer"],
  },
];

export const INITIAL_PETITIONS: DigitalPetition[] = [
  {
    id: "PET-01",
    code: "PET-2026-EGM-01",
    title: "Convocation of Extraordinary General Meeting (EGM) on Stage Equipment Standards",
    description:
      "Formal request for parliamentary floor debate regarding equipment vendor transparency and stage audio specifications under Article 7.",
    category: "EGM_CONVOCATION",
    targetThresholdPercentage: 25.0,
    currentSignatures: 0,
    totalEligibleMembers: 10,
    status: "ACTIVE",
    signedByUser: false,
    deadline: "2026-10-15T23:59:59Z",
  },
];
