import {
  GovernanceUser,
  WhistleblowerDossier,
  FinancialRequisition,
  SongArrangement,
  AttendanceRecord,
  ParliamentaryAgendaItem,
  DigitalPetition,
} from "@/types/governance";

export const INITIAL_PERSONAS: GovernanceUser[] = [
  {
    id: "user-advisor-1",
    legalName: "Dr. Tanvir Ahmed",
    email: "advisor@northsouth.edu",
    studentId: "FAC-10024",
    tier: 1,
    tierLabel: "Tier 1: Faculty Advisor",
    roleTitle: "Faculty Advisor & Tribunal Authority",
    department: "Office of Student Affairs (OSA)",
    isActing: false,
    permissions: ["whistleblower:unblinded", "requisition:tier3:approve", "audit:certify"],
  },
  {
    id: "user-pres-1",
    legalName: "Farhan Rahman",
    email: "president@northsouth.edu",
    studentId: "2011452042",
    tier: 2,
    tierLabel: "Tier 2: Club President",
    roleTitle: "President & Chief Executive Officer",
    department: "Executive Board",
    isActing: false,
    permissions: ["requisition:tier2:dual_sign", "meeting:convoke", "vacancy:appoint"],
  },
  {
    id: "user-vp-1",
    legalName: "Anika Tabassum",
    email: "vp@northsouth.edu",
    studentId: "2021673042",
    tier: 3,
    tierLabel: "Tier 3: Vice President",
    roleTitle: "Vice President (Operations Oversight)",
    department: "Executive Board",
    isActing: false,
    actingRole: "Acting President (Standby)",
    permissions: ["operations:oversight", "logistics:view", "performance:view"],
  },
  {
    id: "user-gs-1",
    legalName: "Tasnim Khan",
    email: "gs@northsouth.edu",
    studentId: "2031892042",
    tier: 3,
    tierLabel: "Tier 3: General Secretary",
    roleTitle: "General Secretary & Parliamentary Custodian",
    department: "Secretariat",
    isActing: false,
    permissions: ["attendance:dispute", "resignation:queue", "minutes:publish"],
  },
  {
    id: "user-treas-1",
    legalName: "Mehedi Hasan",
    email: "treasurer@northsouth.edu",
    studentId: "2022341042",
    tier: 3,
    tierLabel: "Tier 3: Treasurer",
    roleTitle: "Treasurer & Financial Custodian",
    department: "Treasury",
    isActing: false,
    permissions: ["ledger:manage", "requisition:disburse", "petty_cash:monitor"],
  },
  {
    id: "user-music-1",
    legalName: "Samiul Islam",
    email: "music.head@northsouth.edu",
    studentId: "2112456042",
    tier: 4,
    tierLabel: "Tier 4: Music Department Head",
    roleTitle: "Music & Performance Director (Section 12 Lead)",
    department: "Music & Performance",
    isActing: false,
    isCreativeLead: true,
    permissions: ["creative:firewall:write", "repertoire:manage", "vocal:cast"],
  },
  {
    id: "user-mm-1",
    legalName: "Nusrat Jahan",
    email: "mm.head@northsouth.edu",
    studentId: "2121789042",
    tier: 4,
    tierLabel: "Tier 4: Member Management Head",
    roleTitle: "Member Management & Disciplinary Head",
    department: "Member Management",
    isActing: false,
    permissions: ["attendance:track", "showcause:issue", "coordinator:manage"],
  },
  {
    id: "user-member-1",
    legalName: "Afrin Sultana",
    email: "afrin.s@northsouth.edu",
    studentId: "2213456042",
    tier: 5,
    tierLabel: "Tier 5: Active Member",
    roleTitle: "General Assembly Member (Vocal Section)",
    department: "General Assembly",
    isActing: false,
    permissions: ["profile:view", "leave:submit", "parliament:vote", "petition:sign"],
  },
];

export const INITIAL_DOSSIERS: WhistleblowerDossier[] = [
  {
    id: "DOS-2026-001",
    trackingNumber: "WB-NSU-2026-9812",
    targetRole: "President",
    targetName: "Farhan Rahman",
    allegationType: "FINANCIAL_MISCONDUCT",
    summary:
      "Confidential disclosure regarding off-book vendor sponsorship negotiation for the Fall Gala without Treasury pre-clearance.",
    evidenceCount: 4,
    submittedAt: "2026-09-24T14:32:00Z",
    status: "CONFIDENTIAL_REVIEW",
    isAgainstPresident: true,
  },
  {
    id: "DOS-2026-002",
    trackingNumber: "WB-NSU-2026-9844",
    targetRole: "Event Logistics Coordinator",
    targetName: "Rayan Chowdhury",
    allegationType: "ABUSE_OF_POWER",
    summary:
      "Preferential badge distribution during the Spring Concert and circumvention of standard volunteer check-in rosters.",
    evidenceCount: 2,
    submittedAt: "2026-09-27T09:15:00Z",
    status: "PANEL_CONVOKED",
    isAgainstPresident: false,
  },
];

export const INITIAL_REQUISITIONS: FinancialRequisition[] = [
  {
    id: "REQ-2026-081",
    requisitionNumber: "REQ-2026-081",
    tier: 1,
    requestedBy: "Samiul Islam",
    initiatorRole: "Music Department Head",
    department: "Music & Performance",
    amountBDT: 2500,
    purpose: "Emergency XLR balanced cables and 9V phantom batteries for auditorium practice rehearsal",
    vendorName: "Yamaha Music Pro Plaza, Dhanmondi",
    hasEBResolution: false,
    status: "DISBURSED",
    signatures: {
      gsSigned: true,
      gsName: "Tasnim Khan",
      treasurerSigned: true,
      treasurerName: "Mehedi Hasan",
    },
    disbursedAt: "2026-09-28T16:00:00Z",
    voucherDeadlineHours: 28, // 28 hours remaining of 72 hours
    createdAt: "2026-09-28T11:00:00Z",
  },
  {
    id: "REQ-2026-094",
    requisitionNumber: "REQ-2026-094",
    tier: 2,
    requestedBy: "Rayan Chowdhury",
    initiatorRole: "Event Logistics Coordinator",
    department: "Event Logistics",
    amountBDT: 14500,
    purpose: "Sound engineering engineer retainer and specialized direct-box equipment rental for Fall Showcase",
    vendorName: "Studio SoundTech Dhaka",
    hasEBResolution: true,
    status: "PENDING_APPROVAL",
    signatures: {
      gsSigned: true,
      gsName: "Tasnim Khan",
      treasurerSigned: true,
      treasurerName: "Mehedi Hasan",
      presidentSigned: false,
    },
    createdAt: "2026-09-29T10:30:00Z",
  },
  {
    id: "REQ-2026-102",
    requisitionNumber: "REQ-2026-102",
    tier: 3,
    requestedBy: "Farhan Rahman",
    initiatorRole: "Club President",
    department: "Executive Board",
    amountBDT: 48500,
    purpose: "Main Stage Modular Truss Rigging and High-Lumen Moving Head Illumination for NSU Plaza Concert",
    vendorName: "Apex Production Services Ltd.",
    hasEBResolution: true,
    status: "PENDING_APPROVAL",
    signatures: {
      gsSigned: true,
      gsName: "Tasnim Khan",
      treasurerSigned: true,
      treasurerName: "Mehedi Hasan",
      presidentSigned: true,
      presidentName: "Farhan Rahman",
      advisorSigned: false,
    },
    createdAt: "2026-09-29T18:00:00Z",
  },
];

export const INITIAL_REPERTOIRE: SongArrangement[] = [
  {
    id: "SONG-01",
    title: "Dhitang Dhitang Bole",
    genre: "Contemporary Folk Fusion",
    tempoBpm: 118,
    keySignature: "D minor",
    leadVocal: "Afrin Sultana",
    harmonies: ["Soprano: Sadia Noor", "Tenor: Kazi Tanmoy"],
    instrumentation: ["Flute", "Acoustic Guitar", "Cajon", "Dotara"],
    status: "REHEARSAL_READY",
    section12Protected: true,
    lastEditedBy: "Samiul Islam (Music Head)",
  },
  {
    id: "SONG-02",
    title: "O Amar Desher Mati",
    genre: "Patriotic Symphony",
    tempoBpm: 76,
    keySignature: "F major",
    leadVocal: "Tanmoy Roy",
    harmonies: ["Choral SATB Section (16 Voices)"],
    instrumentation: ["Grand Piano", "Violin Ensembles", "Cello"],
    status: "LOCKED_FOR_CONCERT",
    section12Protected: true,
    lastEditedBy: "Samiul Islam (Music Head)",
  },
  {
    id: "SONG-03",
    title: "Amar Shonar Bangla (Overture)",
    genre: "Orchestral Anthem",
    tempoBpm: 84,
    keySignature: "G major",
    leadVocal: "Ensemble Full Choir",
    harmonies: ["Harmonized 4-Part Polyphony"],
    instrumentation: ["Full Acoustic Orchestra", "Bansuri"],
    status: "DRAFT",
    section12Protected: true,
    lastEditedBy: "Samiul Islam (Music Head)",
  },
];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  {
    memberId: "user-member-1",
    memberName: "Afrin Sultana",
    studentId: "2213456042",
    totalSessions: 14,
    attendedSessions: 12,
    excusedLeaves: 2,
    effectivePercentage: 100, // 12 / (14 - 2) = 100%
    consecutiveAbsences: 0,
    showCauseIssued: false,
    status: "IN_GOOD_STANDING",
  },
  {
    memberId: "user-member-2",
    memberName: "Kazi Momin",
    studentId: "2134589042",
    totalSessions: 14,
    attendedSessions: 5,
    excusedLeaves: 0,
    effectivePercentage: 35.7, // < 50% cutoff line!
    consecutiveAbsences: 4,
    showCauseIssued: true,
    status: "DISQUALIFIED_FROM_VOTING",
  },
  {
    memberId: "user-member-3",
    memberName: "Farzana Yasmin",
    studentId: "2314567042",
    totalSessions: 14,
    attendedSessions: 7,
    excusedLeaves: 1,
    effectivePercentage: 53.8, // Just above 50% threshold
    consecutiveAbsences: 1,
    showCauseIssued: false,
    status: "AT_RISK",
  },
  {
    memberId: "user-member-4",
    memberName: "Tanmoy Sen",
    studentId: "2231456042",
    totalSessions: 14,
    attendedSessions: 6,
    excusedLeaves: 0,
    effectivePercentage: 42.8,
    consecutiveAbsences: 3, // 3 consecutive absences threshold triggered!
    showCauseIssued: false,
    status: "AT_RISK",
  },
];

export const INITIAL_PARLIAMENTARY_AGENDAS: ParliamentaryAgendaItem[] = [
  {
    id: "AGENDA-2026-F1",
    agendaCode: "NSU-SOP-AG-04",
    title: "Ratification of Fall 2026 Master Production Budget (166,500 BDT Allocation)",
    description:
      "Formal General Assembly ratification of the Fall 2026 operational budget allocation, ensuring OSA line-item compliance and reserve maintenance.",
    category: "BUDGET_RATIFICATION",
    activeQuorumPercentage: 78.4,
    floorQuorumThreshold: 33.3, // 33% floor quorum
    status: "OPEN",
    votesInFavor: 46,
    votesAgainst: 4,
    abstentions: 2,
    conflictedMembers: ["user-treas-1"], // Treasurer recused on own budget motion
  },
  {
    id: "AGENDA-2026-F2",
    agendaCode: "NSU-SOP-AG-05",
    title: "Mandatory Rehearsal Attendance Policy Amendment (Article 14 Clause B)",
    description:
      "Amendment lowering non-vocal stage crew minimum physical attendance requirements during midterm examination weeks.",
    category: "CONSTITUTIONAL_AMENDMENT",
    activeQuorumPercentage: 74.2,
    floorQuorumThreshold: 33.3,
    status: "OPEN",
    votesInFavor: 38,
    votesAgainst: 12,
    abstentions: 2,
    conflictedMembers: ["user-music-1"], // Music Head recused due to section conflict
  },
];

export const INITIAL_PETITIONS: DigitalPetition[] = [
  {
    id: "PET-01",
    code: "PET-2026-EGM-01",
    title: "Convocation of Extraordinary General Meeting (EGM) on Fall Stage Equipment Rental Standards",
    description:
      "Formal request for parliamentary floor debate regarding equipment vendor transparency and stage audio specifications for NSU Plaza events.",
    category: "EGM_CONVOCATION",
    targetThresholdPercentage: 25.0, // 25% active member requirement
    currentSignatures: 22,
    totalEligibleMembers: 64, // 22/64 = 34.3% -> Threshold Met!
    status: "THRESHOLD_REACHED",
    signedByUser: true,
    deadline: "2026-10-05T23:59:59Z",
  },
  {
    id: "PET-02",
    code: "PET-2026-NO-CONF-02",
    title: "Petition for Review of Department Coordinator Apportionment Formula",
    description:
      "Constitutional review requesting the allocation of an additional coordinator seat for Event Logistics under Article 9.",
    category: "POLICY_REVISION",
    targetThresholdPercentage: 25.0,
    currentSignatures: 12,
    totalEligibleMembers: 64, // 12/64 = 18.7% -> In progress
    status: "ACTIVE",
    signedByUser: false,
    deadline: "2026-10-12T23:59:59Z",
  },
];
